save password in client cookies implemented
COSI-Lab/go-talks pull request #6
Opened 2023-07-06 12:04 UTC by shayanshabani

2023-07-06 13:15 UTC, Grissess reviewed
Fits the bill! Just a few notes, one of which has a parsing concern, but it looks good otherwise.

2023-07-06 15:35 UTC, Alextopher commented
@Grissess did you mean to leave comments? I don't see any

2023-07-07 23:05 UTC, Alextopher requested changes

2023-07-07 23:05 UTC, Alextopher commented on static/site.js
> +        path: "/"
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value

A same site attribute should be set (at least to prevent the warning in the developer console) and I think `Strict` is correct for a secret.

2023-07-18 21:31 UTC, merged